easy_admin:
    site_name: 'ATP Admin Panel'
    list:
        max_results: 50
    entities:
        News:
            class: App\Entity\News
            label: 'News'
            list:
                title: "News"
                fields:
                    - { property: 'id' }
                    - { property: 'title', css_class: 'input-large' }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'createdAt' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title', css_class: 'input-large' }
                    - { property: 'text', label: 'description'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'createdAt' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'Description' }
                    - { property: 'caption', type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'pdf' }
                    - { property: 'pdfFile', type: 'vich_image' }
                    - { property: 'video' }
                    - { property: 'videoFile', type: 'vich_image' }
                    - { property: 'createdAt' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Lessons:
            class: App\Entity\Lessons
            label: 'Sample Lessons'
            list:
                title: "Sample Lessons"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdfHy' }
                    - { property: 'pdfEn' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdfHy' }
                    - { property: 'pdfEn' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'pdfFileHy', type: 'vich_image' }
                    - { property: 'pdfFileEn', type: 'vich_image' }

        Magazine:
            class: App\Entity\Magazine
            label: 'Magazine'
            list:
                title: "Magazine"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdfHy' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdf' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'pdfFileHy', type: 'vich_image' }
                    - { property: 'pdfFileEn', type: 'vich_image' }

        Gallery:
            class: App\Entity\Gallery
            label: 'Gallery'
            list:
                title: "Gallery"
                fields:
                    - { property: 'id' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - { property: 'text', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType'}, label: 'Gallery' }

        Events:
            class: App\Entity\Event
            label: 'Event'
            list:
                title: "Event"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text', label: 'Description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'is_active', label: 'IsActive', type: 'toggle' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'Description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'is_active', label: 'IsActive', type: 'toggle' }
            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'location', type: 'text' }
                    - { property: 'url', label: 'Link' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'Description' }
                    - { property: 'startDate' }
                    - { property: 'endDate' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Slide:
            class: App\Entity\Slide
            label: 'Home Page Slider'
            list:
                title: "Home Page Slider"
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'Subtitle' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'Subtitle' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Team:
            class: App\Entity\Team
            label: 'Team'
            list:
                title: "Team"
                fields:
                    - { property: 'id' }
                    - { property: 'title', label: 'Full Name' }
                    - { property: 'text', label: 'Position' }
                    - { property: 'branch' }
                    - { property: 'number', label: 'Order' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title', label: 'Full Name' }
                    - { property: 'text', label: 'Position' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text', label: 'Full Name' }
                    - { property: 'text', type: 'text', label: 'Position' }
                    - { property: 'branch' , type: 'choice', type_options: {choices: {'CHIVA NURSERY':'CHIVA NURSERY',
                                                                                      'MIRAK NURSERY':'MIRAK NURSERY',
                                                                                      'KHACHPAR NURSERY':'KHACHPAR NURSERY',
                                                                                      'KARIN NURSERY':'KARIN NURSERY',
                                                                                      'ATP YEREVAN, ARMENIA':'ATP YEREVAN, ARMENIA',
                                                                                      'ATP SOUTHERN CALIFORNIA, USA':'ATP SOUTHERN CALIFORNIA, USA',
                                                                                      'ATP BOSTON, MASSACHUSETTS':'ATP BOSTON, MASSACHUSETTS' }}}
                    - { property: 'branchType' , type: 'choice', type_options: {choices: {'atp':'atp', 'nursery':'nursery'}}}
                    - { property: 'number', label: 'Order' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Ambassador:
            class: App\Entity\Ambassador
            label: 'Ambassador'
            list:
                title: "Ambassador"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text_bottom'  }
                    - { property: 'text_top'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text_bottom'  }
                    - { property: 'text_top'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'text_bottom' , type: 'fos_ckeditor' }
                    - { property: 'text_top' , type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text_bottom'
                    - property: 'entityLang.text_top'

        Featured:
            class: App\Entity\Feature
            label: 'Featured Content'
            list:
                title: "Featured Content"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'link_type'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'link', type: 'text' }
                    - { property: 'link_type' , type: 'choice', type_options: {choices: {'Donate':'Donate', 'Read More':'Read More', 'Video':'Video' }}}
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'tag', type_options: { multiple: true } }
                    - { property: 'createdAt', type: 'date' }

            search:
                fields:
                    - property: 'entityLang.title'

        Tag:
            class: App\Entity\Tag
            label: 'Featured Tags'
            list:
                title: "Featured Tags"
                fields:
                    - { property: 'title', label: 'position' }
                    - { property: 'text', label: 'page' }
            show:
            form:
                fields:
                    - { property: 'title', type: 'text',  label: 'position' }
                    - { property: 'text', type: 'text', label: 'page' }
            search:
                fields:
                    - property: 'entityLang.title'

        Donation:
            class: App\Entity\Donation
            label: 'Donation List'
            disabled_actions: ['new', 'edit', 'delete']
            list:
                title: "Donations"
                fields:
                    - { property: 'id' }
                    - { property: 'transactionId', label: 'tr.id' }
                    - { property: 'transactionCode', label: 'tr.code' }
                    - { property: 'type' }
                    - { property: 'amount' }
                    - { property: 'name' }
                    - { property: 'address', label: ' A d d r e s s | n a m e ' }
                    - { property: 'email' }
                    - { property: 'phone' }
                    - { property: 'employer' }
                    - { property: 'certificate' }
                    - { property: 'createdAt' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'amount' }
                    - { property: 'text'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
