easy_admin:
    site_name: 'ATP Admin Panel'
    list:
        max_results: 5
    entities:
        News:
            class: App\Entity\News
            label: 'News'
            list:
                title: "News"
                fields:
                    - { property: 'id' }
                    - { property: 'title', css_class: 'input-large' }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'createdAt' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title', css_class: 'input-large' }
                    - { property: 'text', label: 'description'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'createdAt' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'description' }
                    - { property: 'caption', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'pdf' }
                    - { property: 'pdfFile', type: 'vich_image' }
                    - { property: 'video' }
                    - { property: 'videoFile', type: 'vich_image' }
                    - { property: 'createdAt' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Lessons:
            class: App\Entity\Lessons
            label: 'Sample Lessons'
            list:
                title: "Sample Lessons"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdf' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdfName' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'pdfFile', type: 'vich_image' }

        Magazine:
            class: App\Entity\Magazine
            label: 'Magazine'
            list:
                title: "Magazine"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'magazine' }
                    - { property: 'pdf' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'magazine' }
                    - { property: 'pdf' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'pdfFile', type: 'vich_image' }

        Gallery:
            class: App\Entity\Gallery
            label: 'Gallery'
            list:
                title: "Gallery"
                fields:
                    - { property: 'id' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - { property: 'text', type: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType'}, label: 'Gallery' }

        Events:
            class: App\Entity\Event
            label: 'Event'
            list:
                title: "Event"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'is_active', label: 'isActive', type: 'toggle' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'is_active', label: 'isActive', type: 'toggle' }
            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'location', type: 'text' }
                    - { property: 'linkText', label: 'link' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'description' }
                    - { property: 'startDate' }
                    - { property: 'endDate' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Slide:
            class: App\Entity\Slide
            label: 'Home Page Slider'
            list:
                title: "Home Page Slider"
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'subtitle' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'subtitle' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Team:
            class: App\Entity\Team
            label: 'Team'
            list:
                title: "Team"
                fields:
                    - { property: 'id' }
                    - { property: 'title', label: 'Full Name' }
                    - { property: 'text', label: 'Position' }
                    - { property: 'branches' }
                    - { property: 'number', label: 'order' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text', label: 'Position' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text', label: 'name' }
                    - { property: 'text', type: 'text', label: 'position' }
                    - { property: 'branches' }
                    - { property: 'number', label: 'order' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Ambassador:
            class: App\Entity\Ambassador
            label: 'Ambassador'
            list:
                title: "Ambassador"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text_bottom'  }
                    - { property: 'text_top'  }
                    - { property: 'image', type: 'images', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text_bottom'  }
                    - { property: 'text_top'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'text_bottom' , type: 'fos_ckeditor' }
                    - { property: 'text_top' , type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text_bottom'
                    - property: 'entityLang.text_top'

        Featured:
            class: App\Entity\Feature
            label: 'Featured Content'
            list:
                title: "Featured Content"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'link_type', type: 'choice', type_options: {choices: {'inner':'inner', 'outter':'outter'}}}
                    - { property: 'position'  }
                    - { property: 'image', type: 'images', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'link_type'  }
                    - { property: 'position'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'link', type: 'text' }
                    - { property: 'link_type' , type: 'choice', type_options: {choices: {'inner':'inner', 'outter':'outter'}}}
                    - { property: 'position' , type: 'choice', type_options: {choices: {'first':'first', 'second':'second', 'third':'third' }}}
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'tag', type_options: { multiple: true } }
                    - { property: 'createdAt', type: 'date' }

            search:
                fields:
                    - property: 'entityLang.title'

        Tag:
            class: App\Entity\Tag
            label: 'Featured Tags'
            list:
                title: "Featured Tags"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
            form:
                fields:
                    - { property: 'title' }
            search:
                fields:
                    - property: 'entityLang.title'

        Donation:
            class: App\Entity\Donation
            label: 'Donation Amount'
            disabled_actions: ['new', 'edit']
            list:
                title: "Donations"
                fields:
                    - { property: 'id' }
                    - { property: 'amount' }
                    - { property: 'text'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'amount' }
                    - { property: 'text'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
