easy_admin:
    site_name: 'ATP Admin Panel'
    list:
        max_results: 5
    entities:
        News:
            class: App\Entity\News
            label: 'News'
            list:
                title: "News"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'createdAt' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'description'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'createdAt' }

            form:
                fields:
                    - { property: 'title' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'description' }
                    - { property: 'caption' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'pdf' }
                    - { property: 'pdfFile', type: 'vich_image' }
                    - { property: 'video' }
                    - { property: 'videoFile', type: 'vich_image' }
                    - { property: 'createdAt' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Lessons:
            class: App\Entity\Lessons
            label: 'Sample Lessons'
            list:
                title: "Sample Lessons"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdf' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'pdfName' }

            form:
                fields:
                    - { property: 'title' }
                    - { property: 'pdfFile', type: 'vich_image' }

        Gallery:
            class: App\Entity\Gallery
            label: 'Gallery'
            list:
                title: "Gallery"
                fields:
                    - { property: 'id' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - { property: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType'}, label: 'Gallery' }

        Events:
            class: App\Entity\Event
            label: 'Event'
            list:
                title: "Event"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'is_active', label: 'isActive', type: 'toggle' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'description' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'is_active', label: 'isActive', type: 'toggle' }
            form:
                fields:
                    - { property: 'title'  }
                    - { property: 'location' }
                    - { property: 'linkText', label: 'link' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'description' }
                    - { property: 'startDate' }
                    - { property: 'endDate' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Slide:
            class: App\Entity\Slide
            label: 'Home Page Slider'
            list:
                title: "Home Page Slider"
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text', label: 'subtitle' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title' }
                    - { property: 'text' , type: 'fos_ckeditor', label: 'subtitle' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Team:
            class: App\Entity\Team
            label: 'Team'
            list:
                title: "Team"
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text'  }
                    - { property: 'branches' }
                    - { property: 'number' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title'  }
                    - { property: 'text'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title' , type: 'fos_ckeditor' }
                    - { property: 'text' , type: 'fos_ckeditor' }
                    - { property: 'branches' }
                    - { property: 'number' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text'

        Ambassador:
            class: App\Entity\Ambassador
            label: 'Ambassador'
            list:
                title: "Ambassador"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text_bottom'  }
                    - { property: 'text_top'  }
                    - { property: 'image', type: 'images', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text_bottom'  }
                    - { property: 'text_top'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title' , type: 'fos_ckeditor' }
                    - { property: 'text_bottom' , type: 'fos_ckeditor' }
                    - { property: 'text_top' , type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'
                    - property: 'entityLang.text_bottom'
                    - property: 'entityLang.text_top'

        Featured:
            class: App\Entity\Feature
            label: 'Features'
            list:
                title: "Features"
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'link_type'  }
                    - { property: 'position'  }
                    - { property: 'order'  }
                    - { property: 'image', type: 'images', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'link_type'  }
                    - { property: 'position'  }
                    - { property: 'order'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }

            form:
                fields:
                    - { property: 'title' , type: 'fos_ckeditor' }
                    - { property: 'link' , type: 'fos_ckeditor' }
                    - { property: 'link_type' , type: 'fos_ckeditor' }
                    - { property: 'position' , type: 'fos_ckeditor' }
                    - { property: 'order' , type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
            search:
                fields:
                    - property: 'entityLang.title'

        Donation:
            class: App\Entity\Donation
            label: 'Donation Amount'
            list:
                title: "Donations"
                fields:
                    - { property: 'id' }
                    - { property: 'amount' }
                    - { property: 'text'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'amount' }
                    - { property: 'text'  }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - { property: 'amount' }
                    - { property: 'text' , type: 'fos_ckeditor'  }
                    - { property: 'imageFile', type: 'vich_image' }
